In [2]:
import numpy as np

## Define Variables

In [4]:
R = [
     [5,3,0,1],
     [4,0,0,1],
     [1,1,0,5],
     [1,0,0,4],
     [0,1,5,4],
    ]

R = np.array(R) # 평점이채워진 행렬 
N = len(R)      # Item의수
M = len(R[0])   # 유저의수 
K = 2           # latent feature의 수


np.random.seed(1)#고정된 행렬을 만들기 위한부분, 이부분이 없으면 P가 계속 바뀌게된다. 
P = np.random.rand(N,K) # Item 평가 행렬
print "P : \n", P.shape

np.random.seed(2)
Q = np.random.rand(M,K) # 유저의수 
print "Q : \n", Q.shape

P : 
(5, 2)
Q : 
(4, 2)


## Implementating Matrix Factorization 
steps : the maximum number of steps to perform the optimisation

alpha : the learning rate

beta  : the regularization parameter

In [6]:
def matrix_factorization(R, P, Q, K, alpha, steps=5000,  beta=0.02):
    Q = Q.T
    for step in xrange(steps):
        # Stochastic Gradient Descent with weighted beta regularization(SGD-WR)
        for i in xrange(len(R)):
            for j in xrange(len(R[i])):
                if R[i][j] > 0: # 0은 데이터가 없음(그 item에대한 리뷰 남긴게없음)을 의미
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])#prediction error
                    for k in xrange(K):
                        # gradient descent :weight update
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
                        
        if step % 500 == 0 : 
            print "step : ",step,"\n", np.dot(P,Q) # np.dot(P,Q) = R hat

        # Regularizied 에러 계산
        e = 0
        for i in xrange(len(R)):
            for j in xrange(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2) 
                    for k in xrange(K):
                        #Regularization
                        e = e + (beta/2) * ( pow(P[i][k],2) + pow(Q[k][j],2) )
        if e < 0.001: 
            print(e)
            break
    return P, Q.T

In [7]:
alpha=0.0002
nP, nQ = matrix_factorization(R, P, Q, K, alpha)


step :  0 
[[ 0.20296966  0.54466713  0.41506942  0.5338031 ]
 [ 0.00884124  0.13245921  0.10062453  0.1880709 ]
 [ 0.06707004  0.12204015  0.09317115  0.08856389]
 [ 0.0912679   0.25387071  0.19343875  0.25360412]
 [ 0.18897971  0.45467355  0.34664197  0.41750375]]
step :  500 
[[ 2.49045997  1.70411655  2.24186489  2.84053588]
 [ 1.35187453  0.92642587  1.23334777  1.61524692]
 [ 1.80555219  1.2388137   1.66474611  2.2354851 ]
 [ 1.64550304  1.13014967  1.53068363  2.09766476]
 [ 2.76224475  1.89344089  2.5259766   3.32680862]]
step :  1000 
[[ 3.6074386   1.80081593  3.42820852  2.83782657]
 [ 2.45146845  1.22340763  2.40657425  2.11830793]
 [ 2.53246156  1.26204498  2.87373279  3.14520858]
 [ 2.18505082  1.08883264  2.49716218  2.75732522]
 [ 4.01022894  2.00010832  4.1978243   4.10959773]]
step :  1500 
[[ 4.54241362  2.11059361  3.91582859  1.79405869]
 [ 3.2073698   1.49384419  2.93289363  1.59914175]
 [ 1.82660564  0.88449755  3.259255    4.05519937]
 [ 1.58120355  0.76429496  

## Predicted rating

In [8]:
nR = np.dot(nP, nQ.T)
print nR

[[ 5.01629275  2.87852691  4.97827651  0.99659317]
 [ 3.94768814  2.27031369  4.07714135  0.99643295]
 [ 1.09961811  0.74256771  4.65450497  4.96151174]
 [ 0.95043828  0.63440334  3.78595081  3.9728005 ]
 [ 2.18446742  1.33835856  4.87730323  4.04049655]]


In [9]:
print R #기존의 R 

[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]
